Part of #22: Create MTK3339(GPS) skeleton class
Bruin-Spacecraft-Group/SPARTAN pull request #44
Opened 2021-01-08 00:02 UTC by sweeneyngo

Overview
-----

This PR implements part of #22.
It does the following: 

- Create skeleton for MTK3339 class (mtk3339.cpp & mtk3339.h)
- Initialize MTK3339 sensor in main/main.cpp
- Include files (mtk3339.cpp & mtk3339.h) in main/spartan/CMakeLists.txt

2021-01-11 01:37 UTC, kevinl120 approved these changes

2021-01-13 03:40 UTC, harrisonCassar requested changes
Looks good! Just a minor request below to properly merge with some recent changes.

2021-01-13 03:40 UTC, harrisonCassar commented on Software/spartan/src/sensors/mtk3339.cpp
> +int spartan::MTK3339::poll(MasterDataPacket &dp) { return 0; }
Recently there was some changes to the `Sensor` base class interface implemented in #49... Before merging, we should make sure this skeleton also obeys this update.

2021-01-13 03:40 UTC, harrisonCassar commented on Software/spartan/src/sensors/mtk3339.h
> +        virtual int poll(MasterDataPacket &dp);
(Same as above comment with regards to changed `Sensor` interface).

2024-05-14 13:08 UTC, closed without merging